name: 'Auto Increment Semver Action'
description: 'Generates a new version using Pull Request Labels with Semver'
author: 'Mehmet Can Kanpolat'
inputs:
  identifier:
    required: false
    description: 'identifier for version (beta,alpha..)'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
